# Base image
FROM python:3.12.3

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .


# Run the FastAPI server
CMD ["python", "app/main.py"]