# Base image
FROM python:3.12.3

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the necessary port
EXPOSE 8001

# Run the FastAPI server
CMD ["uvicorn", "main:application", "--host", "0.0.0.0", "--port", "8001"]